import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { ThemeProvider } from "@/components/ui/theme-provider";
import { SupabaseProvider } from "@/components/supabase-provider"
import { IconProvider } from "@/components/icon-provider";
import { TopNavConditional } from "@/components/layout/top-nav-conditional";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { supabaseServer } from "@/lib/supabaseServer";
import React from "react";

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): Promise<React.ReactElement> {
  
  
  const supabase = await supabaseServer();
  const { data: { session } } = await supabase.auth.getSession();

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
          

          <SupabaseProvider initialSession={session}>
          <IconProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <TopNavConditional />
              {children}
            </ThemeProvider>
          </IconProvider>
        </SupabaseProvider>
        </body>
      </html>
    
  );
}
